### ISSUE TITLE
Make fails with "error: ‘casa’ does not name a type"

### ISSUE THREAD

**Issue by mknapp55** [lofar-astron/DP3#160]
I encountered a problem with DP3 when using the version that comes with the lastest KERN lofar package (see below).  

```
NDPPP /home/mknapp/LiLF/parsets/LOFAR_cal/DPPP-flag.parset -vv msin=/mnt/d/lofar/trappist/L567751/L567751_SB263_uv.MS ant.baseline="DE*;FR*;SE*;UK*;IR*;PL*"
log4cplus:ERROR No appenders could be found for logger (LCS.Common).
log4cplus:ERROR Please initialize the log4cplus system properly.
NDPPP: symbol lookup error: /usr/lib/libdppp.so.2: undefined symbol: _ZN5LOFAR15StationResponse21readTileBeamDirectionERKN4casa14MeasurementSetE
```
I thought installing from source to get the lastest release of DP3 might solve the problem.  First, I tried using master and got the error below.  
```
[  0%] Building CXX object CMakeFiles/AOFlaggerStep_OBJ.dir/AOFlaggerStep/AOFlaggerStep.cc.o
In file included from /usr/include/StationResponse/AntennaField.h:36:0,
                 from /usr/include/StationResponse/Station.h:32,
                 from /home/mknapp/DP3/AOFlaggerStep/../DPPP/DPInput.h:36,
                 from /home/mknapp/DP3/AOFlaggerStep/AOFlaggerStep.h:30,
                 from /home/mknapp/DP3/AOFlaggerStep/AOFlaggerStep.cc:24:
/usr/include/StationResponse/ITRFDirection.h:56:13: error: ‘casa’ does not name a type; did you mean ‘cosl’?
     mutable casa::MeasFrame             itsFrame;
             ^~~~
             cosl
/usr/include/StationResponse/ITRFDirection.h:57:13: error: ‘casa’ does not name a type; did you mean ‘cosl’?
     mutable casa::MDirection::Convert   itsConverter;
             ^~~~
             cosl
CMakeFiles/AOFlaggerStep_OBJ.dir/build.make:62: recipe for target 'CMakeFiles/AOFlaggerStep_OBJ.dir/AOFlaggerStep/AOFlaggerStep.cc.o' failed
make[2]: *** [CMakeFiles/AOFlaggerStep_OBJ.dir/AOFlaggerStep/AOFlaggerStep.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/AOFlaggerStep_OBJ.dir/all' failed
make[1]: *** [CMakeFiles/AOFlaggerStep_OBJ.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
I reverted to the v4.0 tag and got almost the same error (below). 
```
[ 40%] Building CXX object CMakeFiles/DPPP_OBJ.dir/DPPP/DPRun.cc.o
In file included from /usr/include/StationResponse/AntennaField.h:36:0,
                 from /usr/include/StationResponse/Station.h:32,
                 from /home/mknapp/DP3/DPPP/DPInput.h:36,
                 from /home/mknapp/DP3/DPPP/MSReader.h:30,
                 from /home/mknapp/DP3/DPPP/DPRun.h:31,
                 from /home/mknapp/DP3/DPPP/DPRun.cc:24:
/usr/include/StationResponse/ITRFDirection.h:56:13: error: ‘casa’ does not name a type; did you mean ‘cosl’?
     mutable casa::MeasFrame             itsFrame;
             ^~~~
             cosl
/usr/include/StationResponse/ITRFDirection.h:57:13: error: ‘casa’ does not name a type; did you mean ‘cosl’?
     mutable casa::MDirection::Convert   itsConverter;
             ^~~~
             cosl
CMakeFiles/DPPP_OBJ.dir/build.make:62: recipe for target 'CMakeFiles/DPPP_OBJ.dir/DPPP/DPRun.cc.o' failed
make[2]: *** [CMakeFiles/DPPP_OBJ.dir/DPPP/DPRun.cc.o] Error 1
CMakeFiles/Makefile2:217: recipe for target 'CMakeFiles/DPPP_OBJ.dir/all' failed
make[1]: *** [CMakeFiles/DPPP_OBJ.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
I installed the dependencies using KERN as per the installation instructions. Cmake found all the required libraries.  I'm working in Ubuntu 18.04 on WSL.

**Comment by aroffringa** [comment]
I think your LOFAR beam library is too old. You need the latest from here: https://github.com/lofar-astron/LOFARBeam

**Comment by mknapp55** [comment]
That appears to have fixed both problems (installation and the error I saw when running the KERN version of DP3).  Thanks!
