### PR TITLE
Make it work with casacore 3.1.1

### LINKED ISSUE #170: Incompatible with latest casacore
As reported by @revoltek:
```
#################
/home/fdg/opt/lofar_190705/DPPP/src/Common/BaselineSelect.cc: In static member function ‘static casacore::Matrix<bool> DP3::BaselineSelect::convert(casacore::Table&, casacore::TableExprNode&, casacore::TableExprNode&, const string&, std::ostream&)’:
/home/fdg/opt/lofar_190705/DPPP/src/Common/BaselineSelect.cc:121:59: error: cannot convert ‘casacore::CountedPtr<casacore::MSSelectionErrorHandler>’ to ‘casacore::MSSelectionErrorHandler*’ in initialization
    MSSelectionErrorHandler* curHandler = MSAntennaParse::thisMSAErrorHandler;
                                                          ^
make[2]: *** [CMakeFiles/Common.dir/Common/BaselineSelect.cc.o] Error 1
make[1]: *** [CMakeFiles/Common.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/fdg/opt/lofar_190705/DPPP/src/DPPP/MSWriter.cc: In member function ‘void DP3::DPPP::MSWriter::createMS(const string&, const DP3::DPPP::DPInfo&, unsigned int, unsigned int)’:
/home/fdg/opt/lofar_190705/DPPP/src/DPPP/MSWriter.cc:286:35: error: ‘SimpleOrderedMap’ was not declared in this scope
      newdesc.adjustHypercolumns (SimpleOrderedMap<String,String>(String()));
                                  ^
/home/fdg/opt/lofar_190705/DPPP/src/DPPP/MSWriter.cc:286:58: error: expected primary-expression before ‘,’ token
      newdesc.adjustHypercolumns (SimpleOrderedMap<String,String>(String()));
                                                         ^
/home/fdg/opt/lofar_190705/DPPP/src/DPPP/MSWriter.cc:286:65: error: expected primary-expression before ‘>’ token
      newdesc.adjustHypercolumns (SimpleOrderedMap<String,String>(String()));
                                                                ^
make[2]: *** [CMakeFiles/DPPP_OBJ.dir/DPPP/MSWriter.cc.o] Error 1
make[1]: *** [CMakeFiles/DPPP_OBJ.dir/all] Error 2
make: *** [all] Error 2
###################
```

### PR DESCRIPTION
**Pull request by tammojan**
This depends on a correct casacore version number in version.h, see
casacore/casacore#942
Fixes #170

### CODE REVIEW

File: DPPP/MSWriter.cc [hunk 1]
```diff
@@ -283,7 +284,13 @@ namespace DP3 {
         }
       }
       // Remove possible hypercolumn definitions.
+// Test for casacore version 3.1.1 or smaller
+#pragma message "BOOST_VERSION=" BOOST_PP_STRINGIZE(CASACORE_VERSION_NUM)
```
Comment (aroffringa) [inline DPPP/MSWriter.cc]: Shouldn't you have removed this (debug) line?

In any case, it's the Casacore version, not the boost version ;)

Comment (tammojan) [reply DPPP/MSWriter.cc]: Oops. Thanks. I was a bit too quick with the merge. Will remove the line.
